# This is a basic workflow to help you get started with Actions

name: Windows-CI

on:
  push:
    branches: 
      - master
    tags:
      - '*'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # https://github.community/t5/GitHub-Actions/How-to-get-just-the-tag-name/td-p/31595/page/2
      - name: Branch name
        id: branch_name
        run: |
          echo ::set-output name=SOURCE_NAME::${GITHUB_REF#refs/*/}
          echo ::set-output name=SOURCE_BRANCH::${GITHUB_REF#refs/heads/}
          echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}

      # https://github.com/marketplace/actions/flutter-action
      - uses: actions/setup-java@v1
        with:
          java-version: "8.x"
      - uses: subosito/flutter-action@v1
        with:
          channel: "dev" # optional, default to: 'stable'
      - run: flutter channel master
      - run: flutter upgrade
      - run: flutter config --enable-windows-desktop
      - run: flutter pub get
      - run: flutter build windows
      - run: npm install tree-node-cli -g
      - run: treee build
      - run: 7z a -tzip wayfless-windows-x64-${{ steps.branch_name.outputs.SOURCE_NAME }}.zip -r .\build\windows\x64\Release\Runner\*
      # https://github.com/xresloader/upload-to-github-release
      - uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: wayfless-windows-x64-${{ steps.branch_name.outputs.SOURCE_NAME }}.zip
          tags: true
          draft: false
          update_latest_release: true